### ISSUE TITLE
Phase 0: repository launching

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/flight-safety-analysis#1]
- [x] Repo creation
- [x] Write a good readme
- [x] How to contribute
- [ ] Function docstrings and documentation
- [x] Split slides into Notebooks:
  - [x] Phases of flight
  - [x] Occurrences
  - [x] Age
  - [x] Evolution
- Others?

**Comment by AlexS12** [comment]
I have just added the two remaining notebooks. Would you mind to have a look? I have just seen yours, I would just try to reduce the imports to the essential ones (some of them are not used in the notebooks)

I will improve the documentation of the functions tomorrow so that we can complete all the intended tasks for this milestone. If you have any comments for the notebooks let me know! :+1:

**Comment by AlexS12** [comment]
@martosc did you have some time to check this? It would be nice to start with the next step!

**Comment by martosc** [comment]
Yes!! I reviewed your part and everything is very understandable. Let's move on to the next step.

**Comment by AlexS12** [comment]
The documentation part is still pending but i will close this issue and postpone it.
